### ISSUE TITLE
[feature] let default plugin is current directory

### ISSUE THREAD

**Issue by Freed-Wu** [google/vimdoc#120]
```
❯ vimdoc
usage: vimdoc [-h] [--version] PLUGIN
vimdoc: error: the following arguments are required: PLUGIN
❯ vimdoc .
```

Why not let default plugin is `.`? Thanks.

**Comment by dbarnett** [comment]
I kinda prefer having it explicit over the small convenience of not having to type `.`.

Might be worth giving a better error with a usage hint when plugin path is missing, though.

**Comment by Freed-Wu** [comment]
OK, I see.

**Comment by dbarnett** [comment]
Turned out argparse didn't make it as easy as I'd expected to add a custom error for that case like "Did you mean to run 'vimdoc .'?" But I have some changes for slightly more self-explanatory help on the PLUGIN arg in #126.
