### ISSUE TITLE
[feature] Support PEP518

### ISSUE THREAD

**Issue by Freed-Wu** [google/vimdoc#128]
According to <https://peps.python.org/pep-0621>, any python project should
store its metadata in `pyproject.toml`, not `.gitlint`, `.yamllint.yaml`, `.vintrc.yml`, `addon-info.json`, or other thing.

Many projects have support PEP621, such as

- <https://github.com/psf/black>
- <https://github.com/codespell-project/codespell>
- <https://github.com/PyCQA/pydocstyle>
- <https://github.com/pypa/setuptools>
- <https://github.com/pypa/setuptools_scm/>
- <https://github.com/pypa/hatch>
- <https://github.com/pypa/flit>
- <https://github.com/python-poetry/poetry>
- ...

So I advise this project can support, too.

Before python3.11, toml support must be provided by third-party package, such as

- <https://github.com/psf/black>: [tomli](https://github.com/psf/black/blob/main/pyproject.toml#L70)
- <https://github.com/codespell-project/codespell>: [tomli](https://github.com/codespell-project/codespell/blob/master/pyproject.toml#L46)
- <https://github.com/PyCQA/pydocstyle>: [toml](https://github.com/PyCQA/pydocstyle/blob/master/setup.py#L11)
- <https://github.com/pypa/setuptools>: [tomli, tomli-w, ini2toml](https://github.com/pypa/setuptools/blob/main/setup.cfg#L72-L81)
- <https://github.com/pypa/setuptools_scm/>: [tomli](https://github.com/pypa/setuptools_scm/blob/main/setup.cfg#L35)
- <https://github.com/pypa/hatch>: [tomli-w, tomlkit](https://github.com/pypa/hatch/blob/master/pyproject.toml#L52-L53)
- <https://github.com/pypa/flit>: [tomli](https://github.com/pypa/flit/blob/main/pyproject.toml#L32)
- <https://github.com/python-poetry/poetry> [tomli, tomlkit](https://github.com/python-poetry/poetry/blob/master/pyproject.toml#L70-L72)
- ...

You can use one as extras_require.

After python3.11, tomllib is a builtin package. Not need install any toml package. Remember `python<3.11` in requirements.txt

**Comment by Freed-Wu** [comment]
it should be https://peps.python.org/pep-0518/#tool-table (right, pep only have a number which make it is hard to remember), It suggests every python tool store their setting to pyproject.tomls tool.

**Comment by dbarnett** [comment]
So are we not talking about PEP621 at all here, just PEP518?

Specifically you're suggesting to move metadata from https://github.com/google/vimdoc/blob/main/setup.py to pyproject.toml, right? And presumably suggesting the same for vroom at https://github.com/google/vroom/blob/main/setup.py? Is there any practical benefit for converting existing metadata into that structure?

**Comment by Freed-Wu** [comment]
It's my fault to remember two PEP's number :cry:

In conclusion, PEP621 let developer change setup.py to pyproject.toml, (from a python script to a data exchange format), PEP518 let deveoper change the setting of a tool written by python to pyproject.toml's `[tool.XXX]`.

## PEP518

Before PEP518, every tool written by python has its own config file, like flake8's `.flake8`, codespell's `.codespellrc`, gitlint's `.gitlint`.

However, these configuration is different format: dosini (.codespellrc), json (addon-info.json), yaml (.yamllint.yml) toml (pyproject.toml) User must learn dosini, json, yaml, toml, even more language to know their syntaxes. PEP518 summon all python developers use `pyproject.toml`, that is flake8 store their configuration to `[tool.flake8]`, codespell store its configuration to `[tool.codespell]`, etc.

In other languages, one configuration file has been accepted broadly, such as nodejs's package.json, julia's project.toml, rust's cargo.toml, etc. PEP518 hope python can use one pyproject.toml to configure all things.

So, if  PEP518 is accepted by vimdoc, it  should be

```toml
[tool.vimdoc]
name=XXX
XXX=XXX
```

## PEP621

PEP621 isn't related to user, it is just related to developer. It let developer change `setup.py` to `pyproject.toml`. It can be another issue to explain why.

**Comment by Freed-Wu** [comment]
Because this package has probability to be rewriten in other language, close it. See <https://github.com/google/vimdoc/issues/118#issuecomment-1328105580>
