### ISSUE TITLE
E492: Not an editor command:  Ydc

### ISSUE THREAD

**Issue by sbrocos** [google/vimdoc#99]
Every time I save a file, show me the message: **E492: Not an editor command:  Ydc** But it's saved.

**Comment by dbarnett** [comment]
Do you believe it's related to the vimdoc tool for some reason? Sounds like you meant to report this on https://github.com/vim/vim/issues or something.

**Comment by wsdjeg** [comment]
@sbrocos `Ydc` this command is a from https://github.com/ianva/vim-youdao-translater

and I think you have autocmd for `BufWritePost` to run this command.
